version: "3"
services:
  tms:
    build: .
    image: "laravels:php-7.4.26"
    container_name: tms
    restart: always
    working_dir: /app
    ports:
      - "${SERVER_PORT:-5200}:${SERVER_PORT:-5200}"
    volumes:
      - .:/app
    entrypoint: |
      bash -c "/usr/local/bin/composer install --optimize-autoloader --no-dev && php /app/artisan migrate --force && /app/bin/laravels start -i"
